BUILD_DATE := $(shell date +%Y%m%d)
BUILD_TIME := $(shell date +%H%M)

ifndef CYCLONE_BUILD_TYPE
    CYCLONE_BUILD_TYPE := UNOFFICIAL
endif

# Set all versions
CYCLONE_BASE_VERSION := 12.1
CYCLONE_PLATFORM_VERSION := Vortex
TARGET_PRODUCT_SHORT := $(subst cyclone_,,$(TARGET_PRODUCT))
CYCLONE_VERSION := CYCLONE-$(CYCLONE_BASE_VERSION)-$(CYCLONE_BUILD_TYPE)-$(TARGET_PRODUCT_SHORT)-$(BUILD_DATE)-$(BUILD_TIME)
ROM_FINGERPRINT := CYCLONE/$(PLATFORM_VERSION)/$(CYCLONE_BUILD_TYPE)/$(BUILD_DATE)$(BUILD_TIME)

ifeq ($(CYCLONE_BUILD_TYPE),OFFICIAL)
    PLATFORM_CYCLONE_VERSION := $(CYCLONE_BASE_VERSION).REL.$(shell date +%m%d%H%M)
else
    PLATFORM_CYCLONE_VERSION := $(CYCLONE_BASE_VERSION).INT.$(shell date +%m%d%H%M)
endif

# Declare it's a Cyclone build
CYCLONE_BUILD := true
